import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://travel.agileway.net/login');
});


test.only('Login to the webpage and order flight withh return', async ({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
    const message = page.locator('#flash_notice');
    await expect(message).toHaveText('Signed in!');
    const fromDropdown = page.locator("[name='fromPort']");
    fromDropdown.selectOption('Sydney');
    const toDropDown = page.locator("[name='toPort']");
    toDropDown.selectOption('New York');
    const departDate = page.locator('#departDay');
    await departDate.click();
    await departDate.selectOption('09');
    const departMonth = page.locator('#departMonth');
    await departMonth.click()
    await departMonth.selectOption('September 2025');
    const returnigDay = page.locator('#returnDay');
    await returnigDay.click();
    await returnigDay.selectOption('24');
    const returningMonth = page.locator('#returnMonth');
    await returningMonth.click();
    await returningMonth.selectOption('April 2026');
    await page.locator('[type="checkbox"]').nth(2).click();
    await page.locator('[value="Continue"]').click();
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[value="visa"]').first().click();
    expect(page.locator('[value="visa"]').first()).toBeChecked();
    await page.locator('[name="card_number"]').fill('123456789121345');
    const expiryMonth = page.locator('[name="expiry_month"]');
    await expiryMonth.click();
    await expiryMonth.selectOption('07');
    const expiryYear = page.locator('[name="expiry_year"]');
    await expiryYear.click();
    await expiryYear.selectOption('2027');
    await page.locator('[value="Pay now"]').click();
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();
   const singdOut = await page.locator('#flash_notice');
   await expect(singdOut).toBeVisible();
   await expect(singdOut).toContainText('Signed out!');
});

test('One way flight', async ({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
    const message = page.locator('#flash_notice');
    await expect(message).toHaveText('Signed in!');
    await page.locator('[value="oneway"]').last().click();
    const fromDropdown = page.locator("[name='fromPort']");
    fromDropdown.selectOption('San Francisco');
    const toDropDown = page.locator("[name='toPort']");
    toDropDown.selectOption('Sydney');
    const departDate = page.locator('#departDay');
    await departDate.click();
    await departDate.selectOption('09');
    const departMonth = page.locator('#departMonth');
    await departMonth.click()
    await departMonth.selectOption('September 2025');
    await page.locator('[type="checkbox"]').nth(2).click();
    await page.locator('[value="Continue"]').click();
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[value="master"]').last().click();
    expect(page.locator('[value="master"]').last()).toBeChecked();
    await page.locator('[name="card_number"]').fill('123456789121345');
    const expiryMonth = page.locator('[name="expiry_month"]');
    await expiryMonth.click();
    await expiryMonth.selectOption('07');
    const expiryYear = page.locator('[name="expiry_year"]');
    await expiryYear.click();
    await expiryYear.selectOption('2027');
    await page.locator('[value="Pay now"]').click();
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();
   const singdOut = await page.locator('#flash_notice');
   await expect(singdOut).toBeVisible();
   await expect(singdOut).toContainText('Signed out!');
});


test('Login to the webpage with incorect user name or password', async ({page})=>{
 const userName = 'agileway';
 const password = 'testW1se';
 const incorrectUserName = 'IncorrectUserName';
 const incorrectPassword = 'incorrectPassword';
 await page.locator('#username').fill(incorrectUserName);
 await page.locator('#password').fill(password);
 await page.locator("[value='Sign in']").click();
 const errorMessage = await page.locator('#flash_alert');
 await expect(errorMessage).toBeVisible();
 await expect(errorMessage).toContainText('Invalid email or password');
 await page.locator('#username').fill(userName);
 await page.locator('#password').fill(incorrectPassword);
 await page.locator("[value='Sign in']").click();
 const errorMessage2 = await page.locator('#flash_alert');
 await expect(errorMessage2).toBeVisible();
 await expect(errorMessage2).toContainText('Invalid email or password');
});

test('Buy ticket with no first name info', async({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
 const fromDropdown = page.locator("[name='fromPort']");
    fromDropdown.selectOption('Sydney');
    const toDropDown = page.locator("[name='toPort']");
    toDropDown.selectOption('New York');
    const departDate = page.locator('#departDay');
    await departDate.click();
    await departDate.selectOption('09');
    const departMonth = page.locator('#departMonth');
    await departMonth.click()
    await departMonth.selectOption('September 2025');
    const returnigDay = page.locator('#returnDay');
    await returnigDay.click();
    await returnigDay.selectOption('24');
    const returningMonth = page.locator('#returnMonth');
    await returningMonth.click();
    await returningMonth.selectOption('April 2026');
    await page.locator('[type="checkbox"]').nth(2).click();
    await page.locator('[value="Continue"]').click();
    await page.locator('[name="passengerFirstName"]').fill('');
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    const noNameError = page.locator('#flash_alert');
    await expect(noNameError).toBeVisible;
    await expect(noNameError).toContainText('Must provide first name')
    await page.locator('[value="visa"]').first().click();
    expect(page.locator('[value="visa"]').first()).toBeChecked();
    await page.locator('[name="card_number"]').fill('123456789121345');
    const expiryMonth = page.locator('[name="expiry_month"]');
    await expiryMonth.click();
    await expiryMonth.selectOption('07');
    const expiryYear = page.locator('[name="expiry_year"]');
    await expiryYear.click();
    await expiryYear.selectOption('2027');
    await page.locator('[value="Pay now"]').click();
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();

});

test('Buy ticket with no last name info', async({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
 const fromDropdown = page.locator("[name='fromPort']");
    fromDropdown.selectOption('Sydney');
    const toDropDown = page.locator("[name='toPort']");
    toDropDown.selectOption('New York');
    const departDate = page.locator('#departDay');
    await departDate.click();
    await departDate.selectOption('09');
    const departMonth = page.locator('#departMonth');
    await departMonth.click()
    await departMonth.selectOption('September 2025');
    const returnigDay = page.locator('#returnDay');
    await returnigDay.click();
    await returnigDay.selectOption('24');
    const returningMonth = page.locator('#returnMonth');
    await returningMonth.click();
    await returningMonth.selectOption('April 2026');
    await page.locator('[type="checkbox"]').nth(2).click();
    await page.locator('[value="Continue"]').click();
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill('');
    await page.locator('[value="Next"]').click();
    const noLastNameError = page.locator('#flash_alert');
    await expect(noLastNameError).toBeVisible;
    await expect(noLastNameError).toContainText('Must provide last name');
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[value="visa"]').first().click();
    expect(page.locator('[value="visa"]').first()).toBeChecked();
    await page.locator('[name="card_number"]').fill('123456789121345');
    const expiryMonth = page.locator('[name="expiry_month"]');
    await expiryMonth.click();
    await expiryMonth.selectOption('07');
    const expiryYear = page.locator('[name="expiry_year"]');
    await expiryYear.click();
    await expiryYear.selectOption('2027');
    await page.locator('[value="Pay now"]').click();
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();

});

test('Buy ticket with no flight selection', async({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
    await page.locator('[value="Continue"]').click();
   const noFlightSelectionError = page.locator('#flash_alert');
    await expect(noFlightSelectionError).toBeVisible;
    await expect(noFlightSelectionError).toContainText('Select flight');
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[value="visa"]').first().click();
    expect(page.locator('[value="visa"]').first()).toBeChecked();
    await page.locator('[name="card_number"]').fill('123456789121345');
    const expiryMonth = page.locator('[name="expiry_month"]');
    await expiryMonth.click();
    await expiryMonth.selectOption('07');
    const expiryYear = page.locator('[name="expiry_year"]');
    await expiryYear.click();
    await expiryYear.selectOption('2027');
    await page.locator('[value="Pay now"]').click();
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();

});

test('Buy ticket with no card into', async ({page})=>{
    const userName = 'agileway';
    const password = 'testW1se';
    const firstName = 'Emma';
    const lastName = 'Klausk';
    await page.locator('#username').fill(userName);
    await page.locator('#password').fill(password);
    await page.locator("[value='Sign in']").click();
    const message = page.locator('#flash_notice');
    await expect(message).toHaveText('Signed in!');
    const fromDropdown = page.locator("[name='fromPort']");
    fromDropdown.selectOption('Sydney');
    const toDropDown = page.locator("[name='toPort']");
    toDropDown.selectOption('New York');
    const departDate = page.locator('#departDay');
    await departDate.click();
    await departDate.selectOption('09');
    const departMonth = page.locator('#departMonth');
    await departMonth.click()
    await departMonth.selectOption('September 2025');
    const returnigDay = page.locator('#returnDay');
    await returnigDay.click();
    await returnigDay.selectOption('24');
    const returningMonth = page.locator('#returnMonth');
    await returningMonth.click();
    await returningMonth.selectOption('April 2026');
    await page.locator('[type="checkbox"]').nth(2).click();
    await page.locator('[value="Continue"]').click();
    await page.locator('[name="passengerFirstName"]').fill(firstName);
    await page.locator('[name="passengerLastName"]').fill(lastName);
    await page.locator('[value="Next"]').click();
    await page.locator('[value="Pay now"]').click();
    const noCardInfoError = page.locator('#flash_alert');
    await expect(noCardInfoError).toBeVisible;
    await expect(noCardInfoError).toContainText('Fill card information');
    const confirmation = page.locator ('#confirmation');
    await expect(confirmation).toContainText('Confirmation');
    const bookingNumber = await page.locator('#booking_number').textContent();
    expect(bookingNumber).not.toBeNull();
    await page.locator('[href="/logout"]').click();
   const singdOut = await page.locator('#flash_notice');
   await expect(singdOut).toBeVisible();
   await expect(singdOut).toContainText('Signed out!');
});